export enum ValidateProfileError {
    SERVER_ERROR = 'SERVER_ERROR',
    NO_USER_DATA = 'NO_USER_DATA',
    INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
    INCORRECT_AGE = 'INCORRECT_AGE',
    INCORRECT_COUNTRY = 'INCORRECT_COUNTRY',
}
